"""Add service_id to Booking

Revision ID: c07e33e5e3ba
Revises: bf3850e45948
Create Date: 2025-07-04 09:57:25.927870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07e33e5e3ba'
down_revision = 'bf3850e45948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_unique_constraint('unique_booking', ['user_id', 'service_id', 'date'])
        batch_op.create_foreign_key('fk_booking_service_id', 'service', ['service_id'], ['id'])
        batch_op.create_foreign_key('fk_booking_payment_id', 'payment', ['payment_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('method')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_booking', type_='unique')
        batch_op.alter_column('category',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('payment_id')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
